### ISSUE TITLE
.scss files load with Sass syntax

### ISSUE THREAD

**Issue by svivian** [P233/Syntax-highlighting-for-Sass#77]
Hey. Just tried this plugin in ST3, but when I open a file with extension `.scss`, it comes up with a red background on all the curly braces. In the syntax menu it's mistakenly using "Sass" instead of the "SCSS" syntax. (The former uses the extension `.sass`.)

**Comment by IanBurry** [comment]
Same issue here. In my case it's in the <style> section of Vue.js component files. It highlights all the curly brackets even when lang="scss"

**Comment by ngeeraldo** [comment]
I am also having the same issue @IanBurry

**Comment by P233** [comment]
Please try open a `.scss` file and then click "View" from the Sublime Text menubar, then choose "Syntax" > "Open all with current extension as..." > "Sass" > "SCSS". It should fix the issue.

@IanBurry Could you let me know the Sublime Text Vue.js plugin you are using? I could investigate this nested snippets highlighting issue.

**Comment by IanBurry** [comment]
It's the "Vuejs Complete Package" [https://github.com/BrainBuzzer/vuejs-sublime-complete](https://github.com/BrainBuzzer/vuejs-sublime-complete)

**Comment by P233** [comment]
It looks like that package adds both "sass" and "scss" scopes to embedded style tag. In this case, the "sass" syntax is always chosen before the "scss" syntax. Remove the following code should solve your issue.

https://github.com/BrainBuzzer/vuejs-sublime-complete/blob/master/vue.tmLanguage#L532-L535
https://github.com/BrainBuzzer/vuejs-sublime-complete/blob/master/vue.tmLanguage#L586-L589

I created an issue on https://github.com/BrainBuzzer/vuejs-sublime-complete/issues/11

**Comment by svivian** [comment]
@P233 Sorry I should have added, I'm aware of the "Open all with current extension as..." option. But the plugin should still get it right without me doing that.

**Comment by P233** [comment]
Indeed. In the previous Sass package, both sass and scss were highlighted by the same syntax definition, and the new package provides two syntax definitions separately for sass and scss. I think Sublime Text somehow remembered to highlight scss with the sass syntax, so it caused this issue after this package taking over the package name "Sass".

Sorry for the inconvenience. This issue shouldn't happen again after setting the "Open all with current extension as..." option.

Peiwen
________________________________
